=pod

=head1 NAME

xkbswitch - keyboard layout switcher for X11

=head1 SYNOPSIS

B<xkbswitch> [I<0|1|2|3>]

=head1 DESCRIPTION

B<xkbswitch> sets (or gets) the current keyboard layout group index in the
range of 0..3 (since 4 group limit is forced by the XKB protocol format).

If no arguments are given, then B<xkbswitch> prints the current keyboard
layout group index.

=head1 SEE ALSO

L<setxkbmap(1)>

=cut
