=pod

=encoding UTF-8

=head1 NAME

pkgman - advanced package management tool

=head1 SYNOPSIS

B<pkgman> [I<COMMAND>] [I<OPTION>]... [I<ARGS>]

=head1 DESCRIPTION

B<pkgman> is a package management tool that provides additional
functionality to basic package management utilities, like
L<pkgmk(8)|https://github.com/zeppe-lin/pkgmk/blob/master/pkgmk.8.pod>,
L<pkgadd(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgutils/pkgadd.8.pod>,
L<pkgrm(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgutils/pkgrm.8.pod>
and
L<pkginfo(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgutils/pkginfo.8.pod>.

=head1 OPTIONS

The following options are common to all commands.  Note that each
command has its own set of specific options and arguments.

=over 8

=item B<--no-std-config>

Ignore F</etc/pkgman.conf>.

=item B<--config>="I<FILE>"

Use alternate configuration file.

=item B<--config-set>="I<STRING>"

Set I<STRING> in configuration, overriding configuration file.

=item B<--config-append>="I<STRING>"

Append I<STRING> to configuration.

=item B<--config-prepend>="I<STRING>"

Prepend I<STRING> to configuration.

=item B<--root>="I<PATH>"

Use I<PATH> as root directory.

=item B<-V>, B<--version>

Print program version and exit.

=item B<-h>, B<--help>

Print the I<COMMAND> synopsis and exit.  If the I<COMMAND> is not
specified and B<-h> or B<--help> is specified as a I<COMMAND>, then
print this manual page.

=back

=head1 COMMANDS

B<pkgman> uses so-called commands, which always have to be the first
non-option argument passed.  The commands can be divided into the
following self-explanatory categories.

=head2 INFORMATIONAL

=over 8

=item L<pkgman-dumpconfig(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-dumpconfig.1.pod>

dump the configuration

=item L<pkgman-list(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-list.1.pod>

print list of available packages

=item L<pkgman-list-dup(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-list-dup.1.pod>

print list of duplicate packages

=item L<pkgman-list-nodependents(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-list-nodependents.1.pod>

print list of packages that no other depends on them

=item L<pkgman-list-locked(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-list-locked.1.pod>

print list of locked packages

=item L<pkgman-list-orphans(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-list-orphans.1.pod>

print list of orphaned packages

=item L<pkgman-printf(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-printf.1.pod>

print formatted list of available packages

=item L<pkgman-info(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-info.1.pod>

print package info

=item L<pkgman-readme(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-readme.1.pod>

print the package's README

=item L<pkgman-path(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-path.1.pod>

print path to package source

=item L<pkgman-isinst(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-isinst.1.pod>

print whether packages are installed or not

=item L<pkgman-current(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-current.1.pod>

print installed package version

=item L<pkgman-diff(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-diff.1.pod>

print the differences between installed and available packages

=back

=head2 DEPENDENCIES

=over 8

=item L<pkgman-mdep(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-mdep.1.pod>

print the missing dependencies of installed packages

=item L<pkgman-dep(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-dep.1.pod>

print dependencies for a package

=item L<pkgman-rdep(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-rdep.1.pod>

print reverse dependencies for a package

=back

=head2 SEARCHING

=over 8

=item L<pkgman-search(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-search.1.pod>

search the packages sources directories for package name

=item L<pkgman-dsearch(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-dsearch.1.pod>

search the packages sources directories for package name/description

=item L<pkgman-fsearch(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-fsearch.1.pod>

search the packages sources directories for a file in package footprint

=back

=head2 INSTALL / UPDATE / REMOVE

=over 8

=item L<pkgman-install(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-install.8.pod>

install package(s)

=item L<pkgman-update(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-update.8.pod>

update installed package(s)

=item L<pkgman-remove(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-remove.8.pod>

remove installed package(s)

=back

=head2 SYSTEM UPDATE

=over 8

=item L<pkgman-sysup(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-sysup.8.pod>

update all outdated packages

=item L<pkgman-lock(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-lock.8.pod>

lock the package(s)

=item L<pkgman-unlock(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-unlock.8.pod>

unlock the package(s)

=back

=head2 FILE OPERATIONS

=over 8

=item L<pkgman-ls(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-ls.1.pod>

print out a listing of the package's directory

=item L<pkgman-cat(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-cat.1.pod>

print out the package's file

=item L<pkgman-edit(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-edit.8.pod>

edit the package's file

=back

=head1 FILES

=over 8

=item F</etc/pkgman.conf>

Configuration file. See
L<pkgman.conf(5)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman.conf.5.pod>
manual page for more information.

=item F</var/lib/pkg/db>

Database of currently installed packages.

=item F</var/lib/pkg/locked>

Database of currently locked packages. Used by
L<pkgman-lock(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-lock.8.pod>,
L<pkgman-unlock(8)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-unlock.8.pod>
and 
L<pkgman-list-locked(1)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman-list-locked.1.pod>.

=back

B<NOTE!> When the B<--root>=I<PATH> option is specified, both
databases location changes to I<PATH/var/lib/pkg/...>.

=head1 SEE ALSO

L<pkgman.conf(5)|https://github.com/zeppe-lin/zeppe-lin/blob/master/core/pkgman/pkgman.conf.5.pod>

=cut

# vim:sw=2:ts=2:sts=2:et:cc=72
# End of file.
