#!/bin/sh -ex

/usr/bin/getent group  tor || /usr/sbin/groupadd -r tor
/usr/bin/getent passwd tor || \
	/usr/sbin/useradd -r -d /var/lib/tor -s /bin/false tor

/usr/bin/passwd -l tor

/bin/chown tor:tor /var/lib/tor
/bin/chown tor:tor /var/log/tor
/bin/chown tor:tor /etc/tor/torrc

# End of file.
