.TH DWMBLOCKS 1 dwmblocks\-VERSION
.SH NAME
dwmblocks \- modular status bar for dwm
.SH SYNOPSIS
.B dwmblocks
.R [ \fB-d\fR \fIDELIM\fR ]
.R [ \fB-p\fR ]
.SH DESCRIPTION
dwmblocks is a modular status bar for dwm written in C.  The statusbar
is made from text output from commandline programs.  Blocks are added
and removed by editing the \fIconfig.h\fR.
.SH OPTIONS
.TP
\fB-d\fR \fIDELIM\fR
Set blocks delimiter.
.TP
\fB-p\fR
Print statusbar to stdout.
.SH SEE ALSO
.BR dwm (1),
.BR dwm60cf (1),
.BR dmenu (1)
