#!/bin/sh -ex

gdk-pixbuf-query-loaders --update-cache

# gtk-update-icon-cache comes with gtk, not with gtk3
if [ -x /usr/bin/gtk-update-icon-cache ]; then
	gtk-update-icon-cache -q -t -f /usr/share/icons/trinity
fi

# End of file.
